// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvzppdr8w9JZ4G1eXoiz-XlywonEJ9aHc',
    appId: '1:495491634966:web:3f9780db624b9c1d21e237',
    messagingSenderId: '495491634966',
    projectId: 'srportfolio-6c702',
    authDomain: 'srportfolio-6c702.firebaseapp.com',
    storageBucket: 'srportfolio-6c702.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZB4vRjHsQ-RSCBjGESEyLEo5EOnHNXLA',
    appId: '1:495491634966:android:71ce610ee5aa47f421e237',
    messagingSenderId: '495491634966',
    projectId: 'srportfolio-6c702',
    storageBucket: 'srportfolio-6c702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9J59E4W3YcXEgnTc346qS9h8M3zIOrv8',
    appId: '1:495491634966:ios:39d83662805d077221e237',
    messagingSenderId: '495491634966',
    projectId: 'srportfolio-6c702',
    storageBucket: 'srportfolio-6c702.firebasestorage.app',
    iosBundleId: 'org.sr.portfolio.srPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9J59E4W3YcXEgnTc346qS9h8M3zIOrv8',
    appId: '1:495491634966:ios:39d83662805d077221e237',
    messagingSenderId: '495491634966',
    projectId: 'srportfolio-6c702',
    storageBucket: 'srportfolio-6c702.firebasestorage.app',
    iosBundleId: 'org.sr.portfolio.srPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvzppdr8w9JZ4G1eXoiz-XlywonEJ9aHc',
    appId: '1:495491634966:web:e45963b16d6e6b6b21e237',
    messagingSenderId: '495491634966',
    projectId: 'srportfolio-6c702',
    authDomain: 'srportfolio-6c702.firebaseapp.com',
    storageBucket: 'srportfolio-6c702.firebasestorage.app',
  );
}
